base_url = "https://ongchi.github.io"
theme = "papermod"
generate_feed = true

taxonomies = [
    { name = "tags", feed = true }
]

[markdown]
highlight_code = true

[extra]

[extra.papermod]
title = "PaperMod"
default_theme = "auto"
theme = "light"
language_direction = "auto"
keywords = []
show_theme_toggle = true
show_scroll_to_top = true
show_code_copy_buttons = true
show_reading_time = true
show_word_count = false
show_post_nav_links = true
show_post_meta = true
default_toc_open = false
edit_post_url = "https://github.com/ongchi/ongchi.github.io/tree/master"
date_format = "%Y-%m-%d"
navigation = [
    { url = "$BASE_URL/archive", title = "Archive" },
    { url = "$BASE_URL/tags", title = "Tags" },
]

home_title = "PaperMod"
home_content = "Welcome to a demo of the PaperMod theme!<br><b>PaperMod</b> is a simple but fast and responsive theme with a useful feature-set that enhances UX.<br>Do give a 🌟 on Github !<br>PaperMod is based on the hugo-PaperMod theme."
social_icons = [
    { url = "https://github.com/ongchi", title = "GitHub", icon = "github" },
    { url = "$BASE_URL/atom.xml", title = "RSS", icon = "rss" },
]
